### ISSUE TITLE
android6.0有问题

### ISSUE THREAD

**Issue by mw0516** [abcmmee/WifiProxy#1]
6.0设置不成功，有好的建议吗

**Comment by abcmmee** [comment]
谢谢您的提醒，这个假日我去把手机升级到Android6.0去试一下，失效的话我再找找办法。有可能是6.0私有API变化了，也有可能是6.0改变WiFi设置时得申请一下权限，我9月26日之前回复您一下~

**Comment by mw0516** [comment]
估计跟6.0这个改变有关系吧。
{你的app现在只能修改那些你创建的WifiConfiguration对象的状态。对于用户或者其它app创建的WifiConfiguration对象，你不能修改或者删除。
以前，如果一个app通过使用disableAllOthers=true的设置调用enableNetwork()，设备会断开其它的网络连接，如蜂窝网络。在这个发行版本里，设备不再会断开其它的网络连接。如果你的app的targetSdkVersion等于或低于20，它会固定到所选择的Wi-Fi网络。如果你的app的targetSdkVersion等于或大于21，使用多网络API(如openConnection(), bindSocket()和新方法bindProcessToNetwork())来确保网络流量是通过所选择的网络。}

**Comment by abcmmee** [comment]
发现确实是您说的这样。而且我还尝试过修改一个复制的WifiConfiguration对象，再用WifiManager.addNetwork()方法添加修改后的WifiConfiguration对象，也添加不进去。看来这个WifiProxy项目到Android6.0算是废了。如果哪天您在Android5之后遇到能用的HTTP代理软件，而且访问HTTPS类型的网站不会报错，麻烦您也告诉我一下~

**Comment by mw0516** [comment]
没问题，如果你找到相应解决办法也别忘告知一声哦

**Comment by abcmmee** [comment]
已经有人解决这个问题了^_^
https://github.com/JarenChow/WiFiProxySwitcher

**Comment by mw0516** [comment]
哇 谢谢你告知
